# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_locked', models.BooleanField(default=False)),
                ('gps_is_active', models.BooleanField(default=False)),
                ('light_sensor_is_active', models.BooleanField(default=False)),
                ('ir_sensor_is_active', models.BooleanField(default=False)),
                ('gyro_sensor_is_active', models.BooleanField(default=False)),
                ('sound_alarm_is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
