# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('is_locked', models.BooleanField(default=False)),
                ('gps_is_active', models.BooleanField(default=False)),
                ('light_sensor_is_active', models.BooleanField(default=False)),
                ('light_sensor_threshold', models.FloatField(default=0.01)),
                ('ir_sensor_is_active', models.BooleanField(default=False)),
                ('ir_sensor_threshold', models.FloatField(default=0.01)),
                ('gyro_sensor_is_active', models.BooleanField(default=False)),
                ('sound_alarm_is_active', models.BooleanField(default=False)),
                ('alarm_duration', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Safezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('radius', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
