# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='alarm_duration',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='setting',
            name='description',
            field=models.CharField(default='Some description', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
